apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: cronjob-ldap-group-sync
  namespace: ldap-sync
spec:
  schedule: '*/15 * * * *'
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/oc
            - adm
            - groups
            - sync
            - --whitelist=/etc/config/whitelist.txt
            - --sync-config=/etc/config/ldap-group-sync.yaml
            - --confirm
            image: registry.redhat.io/openshift4/ose-cli
            imagePullPolicy: Always
            name: cronjob-ldap-group-sync
            volumeMounts:
            - mountPath: /etc/config
              name: ldap-sync-volume
            - mountPath: /etc/secrets
              name: ldap-bind-password
          restartPolicy: Never
          serviceAccountName: ldap-group-syncer
          volumes:
          - configMap:
              defaultMode: 420
              name: ldap-config
            name: ldap-sync-volume
          - name: ldap-bind-password
            secret:
              defaultMode: 420
              secretName: ldap-bind-password